CREATE TYPE "QMQuestionType" AS ENUM ('MULTIPLE_OPTION', 'OPEN_ANSWER', 'MATCHER', 'CLASSIFIER');

CREATE TABLE "QMTopic" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "order" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "QMTopic_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "QMQuestion" (
  "id" TEXT NOT NULL,
  "topicId" TEXT NOT NULL,
  "order" INTEGER NOT NULL,
  "type" "QMQuestionType" NOT NULL,
  "prompt" TEXT NOT NULL,
  "data" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "QMQuestion_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "QMSession" (
  "id" TEXT NOT NULL,
  "topicId" TEXT NOT NULL,
  "completedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "QMSession_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "QMAnswer" (
  "id" TEXT NOT NULL,
  "sessionId" TEXT NOT NULL,
  "questionId" TEXT NOT NULL,
  "answer" JSONB NOT NULL,
  "isCorrect" BOOLEAN,
  "reviewedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "QMAnswer_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "QMQuestion" ADD CONSTRAINT "QMQuestion_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "QMTopic"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QMSession" ADD CONSTRAINT "QMSession_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "QMTopic"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QMAnswer" ADD CONSTRAINT "QMAnswer_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "QMSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QMAnswer" ADD CONSTRAINT "QMAnswer_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "QMQuestion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
